# start:
# 	- docker-compose -f ./docker-compose.local.yml up

# start-build:
# 	- docker-compose -f ./docker-compose.local.yml up --build

# clean-old-images:
# 	- docker rmi $$(docker images -qa -f 'dangling=true')

# getip:
# 	- ipconfig getifaddr en0

# nuclear:
# 	- docker rm -vf $$(docker ps -a -q)
# 	- docker rmi -f $$(docker images -a -q)
# 	- docker system prune --volumes -f