apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k8s
spec:
  selector:
    matchLabel: 
     app: nestjs-k8s
  replicas: 2
  template:
    metadata:
      labels:
        app: nestjs-k8s
    spec:
      container:
        - name: nestjs-k8s
          image: wonyus/rncapi:latest
          ports:
            - containerPort: 8000