export const metricUnit = [
	{ value: 'ym', label: 'Yoctometer (ym)' },
	{ value: 'zm', label: 'Zeptometer (zm)' },
	{ value: 'am', label: 'Attometer (am)' },
	{ value: 'fm', label: 'Femtometer (fm)' },
	{ value: 'pm', label: 'Picometer (pm)' },
	{ value: 'nm', label: 'Nanometer (nm)' },
	{ value: 'μm', label: 'Micrometer (μm)' },
	{ value: 'mm', label: 'Millimeter (mm)' },
	{ value: 'cm', label: 'Centimeter (cm)' },
	{ value: 'dm', label: 'Decimeter (dm)' },
	{ value: 'm', label: 'Meter (m)' },
	{ value: 'dam', label: 'Decameter (dam)' },
	{ value: 'hm', label: 'Hectometer (hm)' },
	{ value: 'km', label: 'Kilometer (km)' },
	{ value: 'Mm', label: 'Megameter (Mm)' },
	{ value: 'Gm', label: 'Gigameter (Gm)' },
	{ value: 'Tm', label: 'Terameter (Tm)' },
	{ value: 'Pm', label: 'Petameter (Pm)' },
	{ value: 'Em', label: 'Exameter (Em)' },
	{ value: 'Zm', label: 'Zettameter (Zm)' },
	{ value: 'Ym', label: 'Yottameter (Ym)' },
	{ value: 'in', label: 'Inch (in)' },
	{ value: 'ft', label: 'Foot (ft)' },
	{ value: 'yd', label: 'Yard (yd)' },
	{ value: 'mi', label: 'Mile (mi)' },
	{ value: 'nmi', label: 'Nautical Mile (nmi)' },
	{ value: 'AU', label: 'Astronomical Unit (AU)' },
	{ value: 'ly', label: 'Light Year (ly)' },
	{ value: 'pc', label: 'Parsec (pc)' },
]
