name: build backend

on:
  push:
    branches: ["main"]
#     paths: ["apps/backend/**"]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        run: |-
         docker buildx build \
            --file ./apps/backend/Dockerfile \
            --platform linux/amd64,linux/arm64 \
            --tag wonyus/api:latest \
            --tag wonyus/api:${{ steps.commit.outputs.short }} \
            --build-arg BUILD_NUMBER=$(git rev-parse --short HEAD) \
            --output type=image,push=true
